Make recursion query string case insensitive (#9)
The python google client was making requests with the recursive query
parameter set to the lowercase "true"

DEBUG:google.auth.transport.requests:Making request: GET
http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true

which caused the storage request to fail with;

File "/usr/local/lib/python3.7/site-packages/google/auth/compute_engine/credentials.py", line 80, in _retrieve_info
    self._service_account_email = info['email']
TypeError: string indices must be integers